config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'wch_lst_lists#index'
  resources :wch_lst_lists, except: [:edit, :update] do
    resources :wch_lst_bookmarks, only: [:new, :create]
    resources :wch_lst_reviews, only: :create
  end
  resources :wch_lst_bookmarks, only: :destroy
  resources :wch_lst_reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wch_lst_bookmark.rb
class WchLstBookmark < ApplicationRecord
  # self.table_name = "wch_lst_bookmarks"
  belongs_to :wch_lst_movie
  belongs_to :wch_lst_list

  validates :comment, length: {minimum: 6}
  validates :wch_lst_movie_id, uniqueness: {scope: :wch_lst_list_id, message: "is already in the list"}
end

app/models/wch_lst_list.rb
class WchLstList < ApplicationRecord
  # self.table_name = "wch_lst_lists"
  has_many :wch_lst_bookmarks, dependent: :destroy
  has_many :wch_lst_movies, through: :wch_lst_bookmarks, dependent: :destroy
  has_many :wch_lst_reviews, dependent: :destroy
  has_one_attached :photo
  validates :name, uniqueness: true, presence: true
end

app/models/wch_lst_movie.rb
class WchLstMovie < ApplicationRecord
  # self.table_name = "wch_lst_movies"
  has_many :wch_lst_bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/wch_lst_review.rb
class WchLstReview < ApplicationRecord
  # self.table_name = "wch_lst_reviews"
  belongs_to :wch_lst_list
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wch_lst_bookmarks_controller.rb
class WchLstBookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = WchLstBookmark.new
  end

  def create
    @bookmark = WchLstBookmark.new(bookmark_params)
    @bookmark.wch_lst_list = @list
    if @bookmark.save
      redirect_to wch_lst_list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to wch_lst_list_path(@bookmark.wch_lst_list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:wch_lst_bookmark).permit(:comment, :wch_lst_movie_id)
  end

  def set_bookmark
    @bookmark = WchLstBookmark.find(params[:id])
  end

  def set_list
    @list = WchLstList.find(params[:wch_lst_list_id])
  end
end

app/controllers/wch_lst_lists_controller.rb
class WchLstListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = WchLstList.all
  end

  def show
    @bookmark = WchLstBookmark.new
    @review = WchLstReview.new(wch_lst_list: @list)
  end

  def new
    @list = WchLstList.new
  end

  def create
    @list = WchLstList.new(list_params)
    if @list.save
      redirect_to wch_lst_list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to wch_lst_lists_path, status: :see_other
  end

  private

  def set_list
    @list = WchLstList.find(params[:id])
  end

  def list_params
    params.require(:wch_lst_list).permit(:name, :photo)
  end
end

app/controllers/wch_lst_reviews_controller.rb
class WchLstReviewsController < ApplicationController
  def create
    @review = WchLstReview.new(review_params)
    @list = WchLstList.find(params[:wch_lst_list_id])
    @review.wch_lst_list = @list
    if @review.save
      redirect_to wch_lst_list_path(@list)
    else
      @bookmark = WchLstBookmark.new
      render 'wch_lst_lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = WchLstReview.find(params[:id])
    @review.destroy
    redirect_to wch_lst_list_path(@review.wch_lst_list)
  end

  private

  def review_params
    params.require(:wch_lst_review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wch_lst_bookmarks_helper.rb
module WchLstBookmarksHelper
end

app/helpers/wch_lst_lists_helper.rb
module WchLstListsHelper
end

app/helpers/wch_lst_reviews_helper.rb
module WchLstReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watch List App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-3">
  <%= link_to root_path do %>
    <%= image_tag "popcorn.png", alt: "alttext", class: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto">
      <li class="nav-item active">
        <%= link_to "My lists", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "New list", new_wch_lst_list_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/wch_lst_bookmarks/_modal.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= wch_lst_list.name %> list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
      </div>

      <%= simple_form_for [wch_lst_list, wch_lst_bookmark] do |f| %>
        <div class="modal-body">
          <%= f.association :wch_lst_movie, collection: WchLstMovie.all.order(:title), prompt: "Select a movie", input_html: { data: { controller: "tom-select" } } %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
        </div>
        <div class="modal-footer">
          <%= f.submit "Add movie", class: "btn btn-flat" %>
          <button type="button" class="btn btn-cancel" data-bs-dismiss="modal">Back</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wch_lst_bookmarks/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :wch_lst_movie, prompt: "Select a movie", input_html: {data: { controller: "tom-select"}} %>
          <%= f.submit class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/wch_lst_lists/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
    <br>
    <h1>Save your favorites movies</h1>
    <br>
    <h3 class="typed-js" data-controller="typed-js"></h3>
  </div>
</div>
<div class="container py-5">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h3 class="mb-0">My Lists</h3>
    <%= link_to "Create a movie list", new_wch_lst_list_path, class: "btn btn-flat" %>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="co-12 col-sm-6 col-md-4 mb-3">
        <%= link_to wch_lst_list_path(list), class:"text-decoration-none" do %>
          <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path('list_background.jpg') %>)">
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <!-- app/views/articles/index.html.erb -->
</div>

app/views/wch_lst_lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'Drama' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/wch_lst_lists/show.html.erb
<div class="position-relative">
  <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : asset_path('list_background.jpg') %>)">
    <h1><%= @list.name %></h1>
  </div>
  <span class="movie-tag"><%= pluralize(@list.wch_lst_movies.size, "movie") %></span>
</div>
<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.wch_lst_movies.empty? %></em></small></span>
    <div>
      <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#new_movie_modal">
        add a movie
      </button>
      <%= link_to "delete this list", wch_lst_list_path(@list), class: "btn btn-cancel", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
    </div>
  </div>
  <div class="row my-2">
    <% @list.wch_lst_movies.each do |movie| %>
      <% bookmark = WchLstBookmark.find_by(wch_lst_list: @list, wch_lst_movie: movie) %>
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= movie.title %> <span class="text-muted font-weight-normal">• <%= movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
              <small class="text-right flex-shrink-0"><%= link_to "delete", wch_lst_bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %></small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <hr class="my-5">
  <div class="row">
    <div class="col-12 col-sm-6">
      <h3>Reviews</h3>
      <% if @list.wch_lst_reviews.empty? %>
        <small><em class="text-muted">Be the first one to review this list</em></small>
      <% end %>
      <% @list.wch_lst_reviews.each do |review| %>
        <div>
          <% review.rating.times do %>
            <i class="fas fa-star star-yellow"></i>
          <% end %>
          <small><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
          <p class="mb-0"><%= review.comment %></p>
        </div>
        <hr>
      <% end %>
    </div>
    <div class="col-12 col-sm-6">
      <div class="bg-white rounded p-3">
        <h5>Add your review</h5>
        <%= simple_form_for [@list, @review] do |f| %>
          <%= f.input :comment, placeholder: "Add your review here..." %>
          <%= f.input :rating, as: :select, collection: (1..5), required: true, prompt: "What's your rating", input_html: { data: { controller: "star-rating" } } %>
          <%= f.submit class:"btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render "wch_lst_bookmarks/modal", wch_lst_list: @list, wch_lst_bookmark: @bookmark %>